name: Build (Godot 4.4.1) → Win/Linux/Web + Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 Godot 4.4.1 无头版 + 导出模板（用 godot-builds 官方 Release）
      - - name: Install Godot CLI & export templates
  run: |
    set -e
    VER=4.4.1
    wget -q https://github.com/godotengine/godot-builds/releases/download/${VER}-stable/Godot_v${VER}-stable_linux.x86_64.zip -O godot.zip
    unzip -q godot.zip
    sudo mv Godot_v${VER}-stable_linux.x86_64 /usr/local/bin/godot
    sudo chmod +x /usr/local/bin/godot
    godot --version

    mkdir -p ~/.local/share/godot/export_templates/${VER}.stable/
    wget -q https://github.com/godotengine/godot-builds/releases/download/${VER}-stable/Godot_v${VER}-stable_export_templates.tpz -O t.tpz
    unzip -q t.tpz -d ~/.local/share/godot/export_templates/${VER}.stable/
    echo "Templates under:" ~/.local/share/godot/export_templates/${VER}.stable/
    ls -l ~/.local/share/godot/export_templates/${VER}.stable/


      # 确认工程可加载（你的 project/ 下有 project.godot）
      - name: Verify project loads
        run: godot --headless --path project --quit

      # 导出 Windows（预设名需与 export_presets.cfg 完全一致：Windows Desktop）
      - name: Export Windows
        run: |
          mkdir -p Build/Windows
          godot --headless --path project --export-release "Windows Desktop" ../Build/Windows/UltimateHacker.exe

      # 导出 Linux（预设名：Linux/X11）
      - name: Export Linux
        run: |
          mkdir -p Build/Linux
          godot --headless --path project --export-release "Linux/X11" ../Build/Linux/UltimateHacker.x86_64
          chmod +x Build/Linux/UltimateHacker.x86_64

      # 导出 Web（需要你有 Web 预设；下面有补丁）
      - name: Export Web
        run: |
          mkdir -p Build/Web
          godot --headless --path project --export-release "Web" ../Build/Web/index.html

      - name: Upload artifacts (Win + Linux + Web)
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            Build/Windows
            Build/Linux
            Build/Web

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: builds
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Web content
        uses: actions/upload-pages-artifact@v3
        with:
          path: Build/Web
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
