- - name: Verify files
  run: |
    set -euo pipefail
    echo "Check required files…"
    test -f project/project.godot             || { echo "❌ missing project/project.godot"; exit 1; }
    test -f project/export_presets.cfg        || { echo "❌ missing project/export_presets.cfg"; exit 1; }
    test -f project/scenes/Main.tscn          || { echo "❌ missing project/scenes/Main.tscn"; exit 1; }
    test -f project/scripts/camera/RTSCamera_Pro.gd || { echo "❌ missing RTSCamera_Pro.gd"; exit 1; }
    echo "✅ required files ok"
