name: Build (Godot 4.4.1) → Win/Linux/Web + Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Godot 4.4.1 CLI + Export Templates
        run: |
          set -e
          VER=4.4.1
          # CLI
          wget -q https://github.com/godotengine/godot-builds/releases/download/${VER}-stable/Godot_v${VER}-stable_linux.x86_64.zip -O godot.zip
          unzip -q godot.zip
          sudo mv Godot_v${VER}-stable_linux.x86_64 /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot
          godot --version
          # Export templates
          mkdir -p ~/.local/share/godot/export_templates/${VER}.stable/
          wget -q https://github.com/godotengine/godot-builds/releases/download/${VER}-stable/Godot_v${VER}-stable_export_templates.tpz -O t.tpz
          unzip -q t.tpz -d ~/.local/share/godot/export_templates/${VER}.stable/
          echo "Templates installed at:"
          ls -l ~/.local/share/godot/export_templates/${VER}.stable/ || true

      - name: Verify project
        run: godot --headless --path project --quit

      - name: Export Windows (preset name must match)
        run: |
          mkdir -p Build/Windows
          godot --headless --path project --export-release "Windows Desktop" ../Build/Windows/UltimateHacker.exe

      - name: Export Linux (preset name must match)
        run: |
          mkdir -p Build/Linux
          godot --headless --path project --export-release "Linux/X11" ../Build/Linux/UltimateHacker.x86_64
          chmod +x Build/Linux/UltimateHacker.x86_64

      - name: Export Web (needs Web preset)
        run: |
          mkdir -p Build/Web
          godot --headless --path project --export-release "Web" ../Build/Web/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            Build/Windows
            Build/Linux
            Build/Web

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: builds
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Web content
        uses: actions/upload-pages-artifact@v3
        with:
          path: Build/Web
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
